name: PabloMurillo
favicon: null
layout_spectrum: 0.6288989626336843
typography_spectrum: 0.8807415913324803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8881222503259778
  lightness: 0.6302534055430442
  saturation: 0.7880328323226422
  rhythmicContrast: 0.7547747483476996
purpose: []
